server.port=8080
spring.application.name=api-gateway

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=delivery-service
spring.cloud.gateway.routes[1].uri=lb://delivery-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/deliveries/**

spring.cloud.gateway.routes[2].id=tracking-service
spring.cloud.gateway.routes[2].uri=lb://tracking-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/tracking/**

spring.cloud.gateway.routes[3].id=admin-service
spring.cloud.gateway.routes[3].uri=lb://admin-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/admin/**

spring.cloud.gateway.routes[4].id=auth-docs
spring.cloud.gateway.routes[4].uri=lb://auth-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/v3/api-docs/auth-service
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/v3/api-docs/auth-service, /v3/api-docs

spring.cloud.gateway.routes[5].id=delivery-docs
spring.cloud.gateway.routes[5].uri=lb://delivery-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/v3/api-docs/delivery-service
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/v3/api-docs/delivery-service, /v3/api-docs

spring.cloud.gateway.routes[6].id=tracking-docs
spring.cloud.gateway.routes[6].uri=lb://tracking-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/v3/api-docs/tracking-service
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/v3/api-docs/tracking-service, /v3/api-docs

spring.cloud.gateway.routes[7].id=admin-docs
spring.cloud.gateway.routes[7].uri=lb://admin-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/v3/api-docs/admin-service
spring.cloud.gateway.routes[7].filters[0]=RewritePath=/v3/api-docs/admin-service, /v3/api-docs

springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/v3/api-docs/auth-service
springdoc.swagger-ui.urls[1].name=Delivery Service
springdoc.swagger-ui.urls[1].url=/v3/api-docs/delivery-service
springdoc.swagger-ui.urls[2].name=Tracking Service
springdoc.swagger-ui.urls[2].url=/v3/api-docs/tracking-service
springdoc.swagger-ui.urls[3].name=Admin Service
springdoc.swagger-ui.urls[3].url=/v3/api-docs/admin-service

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=*
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.enabled=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
